### ISSUE TITLE
building steps

### ISSUE THREAD

**Issue by kornava** [foolab/quran#1]
Hi !
I can't get to build it,
can you mention the building steps and dependencies ?

**Comment by foolab** [comment]
Which platform are you building for?

**Comment by kornava** [comment]
Linux (ubuntu 16.04), qt 5.4

**Comment by foolab** [comment]
You can use the .pro file inside desktop
cd desktop && qmake && make
However the desktop port is not really usable.

**Comment by kornava** [comment]
Even the android version doesn't worked for me (I have everything installed properly).
error : dataprovider.cpp:19: error: metadata.h: No such file or directory
 #include "metadata.h"
                      ^

**Comment by kornava** [comment]
for desktop qmake fails and shows this msg:
Project ERROR: Package fontconfig not found
(fontconfig package is already installed in my system)

**Comment by foolab** [comment]
I need to know the steps you took to compile. What commands did you excute? How did you try to build it?

**Comment by foolab** [comment]
install fontconfig development headers
under ubuntu: sudo apt-get install libfontconfig1-dev

**Comment by kornava** [comment]
Aftre I installed libfontconfig1-dev, I got the same error message for both (desktop and android) :
No such file or directory
#include "metadata.h"

I made a research there and I didn't found any such header file!

Steps I followed :
- Desktop : qmake(shows warnings and errors ( data.qrc': Cannot find file 'quran.idx'
  ) , make)
- Android : Qt creator, build

**Comment by foolab** [comment]
metadata.h is built from data/text so what you need to do is to open data/data.pro and "build it"

cd data && qmake && make
After that you can build desktop, n9, sailfish or Android ports.

Android has a script called android.sh
Adjust the QT_VERSION variable at the top and the ANDROID_NDK_ROOT and ANDROID_SDK_ROOT paths and run it.

Just please note that the Android port can crash sometimes.

**Comment by kornava** [comment]
This what happens when I try to build data project : 
main.cpp:521:30: error: conversion from ‘const size_t {aka const long unsigned int}’ to ‘const QVariant’ is ambiguous
     meta.insert("size", o.len);

**Comment by foolab** [comment]
I did (Or I hope I did) a fix for that error in git master. Please do a git pull and try again.

**Comment by foolab** [comment]
As I said before, the desktop port is not really that good. If you are looking for an Android apk then I can easily build you one and spare you the trouble.

**Comment by kornava** [comment]
I did the pull and I'm getting this : 
../../common/index.cpp:49:43: error: conversion from ‘const long unsigned int’ to ‘const QVariant’ is ambiguous
     s.setValue("len", offsets.at(x).second);

For the android version,actually libav is an empty folder,so I got this error after the script execution: 
./android.sh: line 26: ../../libav/configure: No such file or directory
I need to be able to build it too.

Should I have an environment(OS, Qt version, gcc version..) similar to yours to be able to build it?

**Comment by foolab** [comment]
I fixed that error too and pushed it to git.
The problem is I did not build it for 64bit before.
Anyway, do git submodule init && git submodule update and you should get libav populated.
